DJANGO_WEB/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings

# from app01.views import depart, user, admin, account,  chart, upload, city, catch
from app01.views import homepage,account
from app01.views import user, book, borrow, recommendations, ratingandreview

urlpatterns = [
    # path('admin/', admin.site.urls),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    
    #主页
    path('homepage/',homepage.homepage_homepage),
    path('', homepage.homepage_homepage),


    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('register/', account.logout),
    path('image/code/', account.image_code),




    # 用户管理模块接口
    # path('api/user/login/', user.user_login),
    # path('api/user/logout/', user.user_logout),
    path('api/user/register/', user.user_register),
    path('api/user/get/<int:user_id>/', user.user_get),
    path('api/user/delete/<int:user_id>/', user.user_delete),
    path('api/user/change/<int:user_id>/', user.user_change),
    path('api/user/reset/<int:user_id>/', user.user_reset),
    path('api/user/list/', user.user_list),
    


    # # 图书管理模块接口
    path('api/book/register/', book.book_register),
    path('api/book/get/<int:book_id>/', book.book_get),
    path('api/book/delete/<int:book_id>/', book.book_delete),
    path('api/book/change/<int:book_id>/', book.book_change),
    path('api/book/search/', book.book_search),
    path('api/book/list/', book.book_list),
    


    # # 借阅管理模块接口
    

    path('api/borrow/in/<int:book_id>/', borrow.borrow_in_borrow),
    path('api/borrow/out/<int:record_id>/', borrow.borrow_out_borrow),
    path('api/borrow/delete/<int:record_id>/', borrow.borrow_delete),
    path('api/borrow/change/<int:record_id>/', borrow.borrow_change),
    path('api/borrow/get/<int:record_id>/', borrow.borrow_get),
    path('api/borrow/list/', borrow.borrow_list),
    
    

    # 推荐管理模块接口
    path('api/recommendations/push_random/', recommendations.recommendations_push_random),
    path('api/recommendations/push_score/', recommendations.recommendations_push_score),
    path('api/recommendations/push_count/', recommendations.recommendations_push_count),
    


    # 评分评论模块接口

    path('api/ratingandreview/register/<int:book_id>/', ratingandreview.ratingandreview_register),
    path('api/ratingandreview/delete/<int:record_id>/', ratingandreview.ratingandreview_delete),
    path('api/ratingandreview/change/<int:record_id>/', ratingandreview.ratingandreview_change),
    path('api/ratingandreview/get/<int:record_id>/', ratingandreview.ratingandreview_get),
    path('api/ratingandreview/list/', ratingandreview.ratingandreview_list),





















    







    # # 部门管理
    # path('depart/list/', depart.depart_list),
    # path('depart/add/', depart.depart_add),
    # path('depart/<int:nid>/edit/', depart.depart_edit),
    # path('depart/<int:nid>/delete/', depart.depart_delete),
    # path('depart/multi/', depart.depart_multi),



    # # 数据统计
    # path('chart/list/', chart.chart_list),
    # path('chart/bar/', chart.chart_bar),
    # path('chart/pie/', chart.chart_pie),
    # path('chart/line/', chart.chart_line),
    # path('chart/highcharts/', chart.highcharts),

    

    # # 监测站管理
    # path('city/list/', city.city_list),
    # path('city/add/', city.city_add),
    # path('city/<int:nid>/edit/', city.city_edit),
    # path('city/<int:nid>/delete/', city.city_delete),
    # path('city/<int:nid>/map/', city.city_map),
    # path('city/map/all', city.city_map_all),
    

    # #采集信息
    # path('catch/list/', catch.catch_list),
    # path('catch/add/', catch.catch_add),
    # path('catch/<int:nid>/edit/', catch.catch_edit),
    # path('catch/<int:nid>/delete/', catch.catch_delete),
    # path('catch/<int:nid>/capture/', catch.catch_capture),
    # path('catch/capture/all/', catch.catch_capture_all),


    

    
    
    # 调试
    # path('tt/', chart.tt),

]

app01/models.py
from django.db import models

class User(models.Model):
    """ 用户表 """
    user_id = models.AutoField(verbose_name="用户ID", primary_key=True)
    username = models.CharField(verbose_name="用户名", max_length=32, unique=True)
    password = models.CharField(verbose_name="密码", max_length=128)
    email = models.EmailField(verbose_name="邮箱", null=True, blank=True)
    phone = models.CharField(verbose_name="联系电话", max_length=15, null=True, blank=True)
    registration_date = models.DateTimeField(verbose_name="注册日期", auto_now_add=True)
    
    ROLE_CHOICES = (
        (1, "普通用户"),
        (2, "管理员"),
        (3, "ROOT"),
    )
    role = models.SmallIntegerField(verbose_name="角色", choices=ROLE_CHOICES, default=1, null=True, blank=True)

    def __str__(self):
        return self.username

class Book(models.Model):
    """ 图书表 """
    book_id = models.AutoField(verbose_name="图书ID", primary_key=True)
    book_name = models.CharField(verbose_name="图书名", max_length=64)
    author = models.CharField(verbose_name="作者", max_length=64)
    publisher = models.CharField(verbose_name="出版社", max_length=64)
    category = models.CharField(verbose_name="分类", max_length=32)
    stock_quantity = models.IntegerField(verbose_name="库存数量")
    borrow_count = models.IntegerField(verbose_name="借阅次数", default=0)
    score = models.DecimalField(verbose_name="评分", max_digits=3, decimal_places=2, default=0.00)
    img = models.FileField(verbose_name="图书图片展示", max_length=128, upload_to='book/', default='book/default.jpg')

    def __str__(self):
        return self.book_name


class BorrowRecord(models.Model):
    """ 借阅表 """
    record_id = models.AutoField(verbose_name="记录ID", primary_key=True)
    user_id = models.ForeignKey(User, verbose_name="用户ID", on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, verbose_name="图书ID", on_delete=models.CASCADE)
    borrow_date = models.DateTimeField(verbose_name="借阅日期", auto_now_add=True)
    return_date = models.DateTimeField(verbose_name="归还日期", null=True, blank=True)
    
    STATUS_CHOICES = (
        (1, "借阅中"),
        (2, "已归还"),
        (3, "逾期"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=STATUS_CHOICES, default=1)

    def __str__(self):
        return f"{self.user_id.username} - {self.book_id.book_name}"

class ScoreRecord(models.Model):
    """ 评分和评论表 """
    record_id = models.AutoField(verbose_name="记录ID", primary_key=True)
    user_id = models.ForeignKey(User, verbose_name="用户ID", on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, verbose_name="图书ID", on_delete=models.CASCADE)
    rating = models.DecimalField(verbose_name="评分", max_digits=2, decimal_places=1)
    review = models.TextField(verbose_name="评论", null=True, blank=True)

    def __str__(self):
        return f"{self.user_id.username} - {self.book_id.book_name} - {self.rating}"


































# from django.db import models


# class XX(models.Model):
#     title = models.CharField(verbose_name="名称", max_length=32)
#     image = models.FileField(verbose_name="头像", upload_to="avatar/")


# class Admin(models.Model):
#     """ 管理员 """
#     username = models.CharField(verbose_name="用户名", max_length=32)
#     password = models.CharField(verbose_name="密码", max_length=128)

#     def __str__(self):
#         return self.username


# class Department(models.Model):
#     """ 部门表 """
#     name = models.CharField(verbose_name='部门', max_length=32)

#     def __str__(self):
#         return self.name


# class UserInfo(models.Model):
#     """ 员工表 """
#     name = models.CharField(verbose_name="姓名", max_length=16)
#     password = models.CharField(verbose_name="密码", max_length=64)
#     age = models.IntegerField(verbose_name="年龄")
#     account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
#     # create_time = models.DateTimeField(verbose_name="入职时间")
#     create_time = models.DateTimeField(verbose_name="入职时间")

#     # 无约束
#     # depart_id = models.BigIntegerField(verbose_name="部门ID")
#     # 1.有约束
#     #   - to，与那张表关联
#     #   - to_field，表中的那一列关联
#     # 2.django自动
#     #   - 写的depart
#     #   - 生成数据列 depart_id
#     # 3.部门表被删除
#     # ### 3.1 级联删除
#     depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE)
#     # ### 3.2 置空
#     # depart = models.ForeignKey(to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)

#     # 在django中做的约束
#     gender_choices = (
#         (1, "男"),
#         (2, "女"),
#         (3, "其他"),
#     )
#     gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices, null=True)



# class City(models.Model):
#     """ 监测站 """
#     name = models.CharField(verbose_name="监测站名称", max_length=32,unique=True)
#     count = models.IntegerField(verbose_name="终端数量")
#     jingdu = models.FloatField(verbose_name="经度")
#     weidu = models.FloatField(verbose_name="纬度")
    
#     #info
#     linkuser = models.CharField(verbose_name="联系人", max_length=32,null=True,blank=True)
#     linkphone = models.CharField(verbose_name="联系人手机", max_length=11,null=True,blank=True)
#     linkpath = models.CharField(verbose_name="联系人信息", max_length=64,null=True,blank=True)

#     # 本质上数据库也是CharField，自动保存数据。
#     img = models.FileField(verbose_name="监测站图片展示", max_length=128, upload_to='city/')



# class Catch(models.Model):
#     """ 采集信息 """

#     #采集信息 温度、风速、湿度、PM25 等
#     name = models.CharField(verbose_name="来源监测站", max_length=32)
#     wendu = models.FloatField(verbose_name="温度")
#     fengsu = models.FloatField(verbose_name="风速")
#     shidu = models.FloatField(verbose_name="湿度")
#     pm25 = models.FloatField(verbose_name="PM2.5")

#     # create_time = models.DateField(verbose_name="创建时间")
#     create_time = models.DateTimeField(verbose_name="创建时间")
    
    

app01/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from django import forms
from io import BytesIO

from app01.utils.code import check_code
from app01 import models
from app01.utils.bootstrap import BootStrapForm
from app01.utils.encrypt import md5


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )

    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def login(request):
    """ 登录 """
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        

        # 验证码的校验
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {'form': form})

        # 去数据库校验用户名和密码是否正确，获取用户对象、None
        # user_object = models.Admin.objects.filter(username=xxx, password=xxx).first()
        user_object = models.User.objects.filter(**form.cleaned_data).first()

        print("qwe")

        print(form.cleaned_data.get('username'))
        print(form.cleaned_data.get('password'))
        # print(form)

        if not user_object:
            form.add_error("password", "用户名或密码错误")
            # form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；在写入到session中；
        request.session["info"] = {'id': user_object.user_id, 'name': user_object.username, 'role': user_object.role}
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect("/homepage/")

    return render(request, 'login.html', {'form': form})


def image_code(request):
    """ 生成图片验证码 """

    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给Session设置60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


def logout(request):
    """ 注销 """

    request.session.clear()

    return redirect('/homepage/')

app01/views/homepage.py
from django.shortcuts import render
from app01 import models

def homepage_homepage(request):
    """ 首页视图 """
    recommended_books = models.Book.objects.order_by('-score')[:6]  # 按评分推荐前 6 本书
    latest_borrows = models.BorrowRecord.objects.order_by('-borrow_date')[:6]  # 最新借阅记录前 6 条
    user_info = request.session.get("info", {})
    if user_info:
        user_id = user_info.get("id")
        user = models.User.objects.get(user_id=user_id)
        user_reviews = models.ScoreRecord.objects.filter(user_id=user_id)
    else:
        user = None
        user_reviews = []

    context = {
        'recommended_books': recommended_books,
        'latest_borrows': latest_borrows,
        'user': user,
        'user_reviews': user_reviews,
    }
    return render(request, 'homepage.html', context)

app01/views/recommendations.py
import random
from django.shortcuts import render
from django.http import JsonResponse
from app01 import models
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.pagination import Pagination

from django import forms
from django.core.exceptions import ValidationError
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.encrypt import md5
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination


from django.shortcuts import render
from app01 import models
from random import sample

def recommendations_push_random(request):
    """ 随机推荐书籍 """
    title = f"推荐书籍--随机推荐"
    books = list(models.Book.objects.all())
    recommended_books = sample(books, min(len(books), 10))  # 随机推荐最多10本书
    return render(request, 'recommendations_list.html', {'books': recommended_books, 'title': title})

def recommendations_push_score(request):
    """ 按评分推荐书籍 """
    title = f"推荐书籍--评分推荐"
    recommended_books = models.Book.objects.all().order_by('-score')[:10]  # 按评分推荐前10本书
    return render(request, 'recommendations_list.html', {'books': recommended_books, 'title': title})

def recommendations_push_count(request):
    """ 按借阅次数推荐书籍 """
    title = f"推荐书籍--订阅推荐"
    recommended_books = models.Book.objects.all().order_by('-borrow_count')[:10]  # 按借阅次数推荐前10本书
    return render(request, 'recommendations_list.html', {'books': recommended_books, 'title': title})

app01/templates/borrow_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <h2 class="text-center">借阅记录</h2>
    <div style="margin-bottom: 10px" class="clearfix">
        <a class="btn btn-success" href="/api/book/list/">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            去借书
        </a>
        <!-- Modify here to use session username as search data -->
        <a class="btn btn-success" href="/api/borrow/list/?find_kind=1&status=1&q={{ request.session.info.name }}">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            我要还书
        </a>
        <div style="float: right;">
            <form method="get" class="form-inline">
                <div class="input-group">
                    <div class="form-group">
                        <select name="find_kind" class="form-control">
                            <option value="0" {% if find_kind == 0 %}selected{% endif %}>所有字段</option>
                            <option value="1" {% if find_kind == 1 %}selected{% endif %}>用户</option>
                            <option value="2" {% if find_kind == 2 %}selected{% endif %}>图书</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <select name="status" class="form-control">
                            <option value="" {% if status_filter == "" %}selected{% endif %}>任意借阅状态</option>
                            <option value="1" {% if status_filter == "1" %}selected{% endif %}>借阅中</option>
                            <option value="2" {% if status_filter == "2" %}selected{% endif %}>已归还</option>
                            <option value="3" {% if status_filter == "3" %}selected{% endif %}>逾期</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="text" name="q" class="form-control" placeholder="关键字" value="{{ search_data }}">
                    </div>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            借阅记录列表
        </div>
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>用户</th>
                <th>图书</th>
                <th>图书封面</th>
                <th>借阅日期</th>
                <th>归还日期</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <th>{{ obj.record_id }}</th>
                    <td>{{ obj.user_id.username }}</td>
                    <td>{{ obj.book_id.book_name }}</td>
                    <td>
                        <img src="{{ obj.book_id.img.url }}" style="height: 80px;">
                    </td>
                    <td>{{ obj.borrow_date }}</td>
                    <td>{{ obj.return_date }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/api/borrow/out/{{ obj.record_id}}/">归还</a>
                        <a class="btn btn-primary btn-xs" href="/api/borrow/change/{{ obj.record_id }}/">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/api/borrow/delete/{{ obj.record_id }}/">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <ul class="pagination">
        {{ page_string }}
    </ul>
</div>
{% endblock %}

app01/templates/change.html
{% extends 'layout.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ title }} </h3>
            </div>
            <div class="panel-body">
                <!-- <form method="post" novalidate > -->
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>

                

            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            // $('#datetime').datepicker({
            //     format: 'yyyy-mm-dd',
            //     startDate: '0',
            //     language: "zh-CN",
            //     autoclose: true
            // });
            // $('.datepicker').datepicker({
            //     format: 'yyyy-mm-dd',   // 设置日期格式
            //     startDate: '0d',        // 设置可以选择的起始日期
            //     language: 'zh-CN',      // 设置语言为中文
            //     autoclose: true,        // 选择后自动关闭
            //     todayHighlight: true,   // 高亮今天的日期
            //     clearBtn: true,         // 显示清除按钮
            //     forceParse: false       // 如果为false，非格式化日期将不会自动格式化
            // });
            // $('#datetime').datepicker({
            //         format: 'yyyy-mm-dd hh:ii:ss', // 设置日期和时间格式，包含秒
            //         // startDate: new Date(),      // 设置可以选择的起始日期时间
            //         language: 'zh-CN',            // 设置语言为中文
            //         autoclose: true,              // 选择后自动关闭
            //         todayBtn: true,               // 显示今天按钮
            //         minuteStep: 5,                // 时间选择的分钟步长
            //         secondStep: 5,                // 时间选择的秒钟步长
            //         pickerPosition: "bottom-left", // 选择器的位置
            //         forceParse: false             // 如果为false，非格式化日期时间将不会自动格式化
            //     });


        })
    </script>
{% endblock %}

app01/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

app01/templates/homepage.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center">欢迎来到图书管理系统</h1>
    <div class="row">
        <div class="col-md-8">
            <div class="jumbotron">
                <h2 class="text-center">推荐图书</h2>
                <div class="row" style="display: flex; flex-wrap: wrap;">
                    {% for book in recommended_books %}
                        <div class="col-sm-6 col-md-4" style="display: flex;">
                            <div class="thumbnail" style="flex: 1; display: flex; flex-direction: column; justify-content: space-between;">
                                <img src="{{ book.img.url }}" alt="{{ book.book_name }}" class="img-thumbnail" style="height: 200px; object-fit: cover;">
                                <div class="caption" style="line-height: 0.3; font-size: 0.9em; flex: 1;">
                                    <h3 style="font-size: 1.5em;">{{ book.book_name }}</h3>
                                    <p style="font-size: 1.0em;"><strong>作者:</strong> {{ book.author }}</p>
                                    <p style="font-size: 1.0em;"><strong>评分:</strong> {{ book.score }}</p>
                                    <p style="font-size: 1.0em;"><strong>借阅次数:</strong> {{ book.borrow_count }}</p>
                                    <p style="font-size: 1.0em;"><strong>出版社:</strong> {{ book.publisher }}</p>
                                    <p class="btn-container">
                                        <a class="btn btn-primary btn-xxs" href="/api/borrow/in/{{ book.book_id }}/">借阅</a>
                                        <a class="btn btn-primary btn-xxs" href="/api/ratingandreview/register/{{ book.book_id }}/">评分评论</a>
                                        <a class="btn btn-primary btn-xxs" href="/api/ratingandreview/list/?find_kind=2&q={{ book.book_name }}">查看评分评论</a>
                                        <a class="btn btn-primary btn-xxs" href="/api/book/change/{{ book.book_id }}/">编辑</a>
                                        <a class="btn btn-danger btn-xxs" href="/api/book/delete/{{ book.book_id }}/">删除</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            

            <div class="jumbotron">
                <h2 class="text-center">最新借阅记录</h2>
                <div class="row" style="display: flex; flex-wrap: wrap;">
                    {% for record in latest_borrows %}
                        <div class="col-sm-6 col-md-4" style="display: flex;">
                            <div class="thumbnail" style="flex: 1; display: flex; flex-direction: column; justify-content: space-between;">
                                <div class="caption" style="font-size: 0.9em; flex: 1;">
                                    <h3 style="font-size: 1.2em;">{{ record.user_id.username }} 借阅了 {{ record.book_id.book_name }}</h3>
                                    <p style="font-size: 1.0em;"><strong>借阅日期:</strong> {{ record.borrow_date }}</p>
                                    <p style="font-size: 1.0em;"><strong>归还日期:</strong> {{ record.return_date|default:"未归还" }}</p>
                                    <p style="font-size: 1.0em;"><strong>状态:</strong> {{ record.get_status_display }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>


        </div>

        <div class="col-md-4">
            {% if user %}
                <div class="panel panel-default">
                    <div class="panel-heading text-center">
                        <h3>个人信息</h3>
                    </div>
                    <div class="panel-body">
                        <p><strong>用户名:</strong> {{ user.username }}</p>
                        <p><strong>邮箱:</strong> {{ user.email }}</p>
                        <p><strong>电话:</strong> {{ user.phone }}</p>
                        <p><strong>注册日期:</strong> {{ user.registration_date }}</p>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading text-center">
                        <h3>我的评分评论</h3>
                    </div>
                    <div class="panel-body">
                        {% if user_reviews %}
                            <ul class="list-group">
                                {% for review in user_reviews %}
                                    <li class="list-group-item">
                                        <strong>{{ review.book_id.book_name }}:</strong> {{ review.rating }} 分
                                        <p>{{ review.review }}</p>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>没有评分和评论</p>
                        {% endif %}
                    </div>
                </div>
            {% else %}
                <div class="alert alert-info text-center">
                    请<a href="/login/">登录</a>以查看个人信息和评论
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
        <a href="/api/user/register/" class="btn btn-primary" style="background-color: rgb(230, 195, 0);">注册</a>
        <!-- <a href="/homepage/" class="btn btn-primary" style="margin-left: 10px;">访客进入</a> -->
        <!-- <div style="float: left;">
            <a href="/api/user/register/" class="btn btn-primary" style="background-color: rgb(239, 216, 90);">注册</a>
        </div> -->
        <div style="float: right;">
            <!-- <a href="/api/user/register/" class="btn btn-primary" style="background-color: rgb(239, 216, 90);">注册</a> -->
            <a href="/homepage/" class="btn btn-primary" style="background-color: green;">访客进入</a>
        </div>
          
    </form>
</div>

</body>
</html>